# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/falli/Downloads/lab6_2_provided/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_block/mb_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block || ORIG_REF_NAME==mb_block} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_1/mb_block_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_1 || ORIG_REF_NAME==mb_block_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_v10_1/mb_block_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_v10_1 || ORIG_REF_NAME==mb_block_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_v10_1/mb_block_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_v10_1 || ORIG_REF_NAME==mb_block_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_dlmb_bram_if_cntlr_1/mb_block_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_block_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_ilmb_bram_if_cntlr_1/mb_block_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_block_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_lmb_bram_1/mb_block_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_lmb_bram_1 || ORIG_REF_NAME==mb_block_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_xbar_1/mb_block_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_xbar_1 || ORIG_REF_NAME==mb_block_xbar_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_periph_1/mb_block_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_block_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_intc_1/mb_block_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_block_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_xlconcat_0/mb_block_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_block_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_mdm_1_1/mb_block_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_mdm_1_1 || ORIG_REF_NAME==mb_block_mdm_1_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_clk_wiz_1_1/mb_block_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_clk_wiz_1_1 || ORIG_REF_NAME==mb_block_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_rst_clk_wiz_1_100M_1/mb_block_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_block_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_gpio_0_4/mb_block_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_gpio_0_4 || ORIG_REF_NAME==mb_block_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_uartlite_0_1/mb_block_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_uartlite_0_1 || ORIG_REF_NAME==mb_block_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_gpio_1_0 || ORIG_REF_NAME==mb_block_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_gpio_0_5/mb_block_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_gpio_0_5 || ORIG_REF_NAME==mb_block_axi_gpio_0_5} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_timer_0_1/mb_block_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_timer_0_1 || ORIG_REF_NAME==mb_block_axi_timer_0_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_quad_spi_0_1/mb_block_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_quad_spi_0_1 || ORIG_REF_NAME==mb_block_axi_quad_spi_0_1} -quiet] -quiet

# XDC: c:/Users/falli/385/lab6_1/lab6_1.gen/sources_1/bd/mb_block/mb_block_ooc.xdc
