# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/falli/385/lab6_1/lab6_1.srcs/sources_1/ip/music_bram/music_bram.xci
# IP: The module: 'music_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/falli/385/lab6_1/lab6_1.gen/sources_1/ip/music_bram/music_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'music_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/falli/385/lab6_1/lab6_1.srcs/sources_1/ip/music_bram/music_bram.xci
# IP: The module: 'music_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/falli/385/lab6_1/lab6_1.gen/sources_1/ip/music_bram/music_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'music_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
